"""Database Initialize

Revision ID: 18af61580e13
Revises: 
Create Date: 2025-05-11 23:08:06.514714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18af61580e13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm-app',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='app_id_pk')
    )
    with op.batch_alter_table('llm-app', schema=None) as batch_op:
        batch_op.create_index('app_account_id_idx', ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm-app', schema=None) as batch_op:
        batch_op.drop_index('app_account_id_idx')

    op.drop_table('llm-app')
    # ### end Alembic commands ###
