"""Added status to app llm-table

Revision ID: 1a49fe25a4d6
Revises: 18af61580e13
Create Date: 2025-05-11 23:25:13.505126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a49fe25a4d6'
down_revision = '18af61580e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm-app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm-app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
